(function(e, a) { for(var i in a) e[i] = a[i]; }(exports, /******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};
/******/
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/
/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId]) {
/******/ 			return installedModules[moduleId].exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			i: moduleId,
/******/ 			l: false,
/******/ 			exports: {}
/******/ 		};
/******/
/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
/******/
/******/ 		// Flag the module as loaded
/******/ 		module.l = true;
/******/
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/
/******/
/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;
/******/
/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;
/******/
/******/ 	// define getter function for harmony exports
/******/ 	__webpack_require__.d = function(exports, name, getter) {
/******/ 		if(!__webpack_require__.o(exports, name)) {
/******/ 			Object.defineProperty(exports, name, { enumerable: true, get: getter });
/******/ 		}
/******/ 	};
/******/
/******/ 	// define __esModule on exports
/******/ 	__webpack_require__.r = function(exports) {
/******/ 		if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
/******/ 			Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
/******/ 		}
/******/ 		Object.defineProperty(exports, '__esModule', { value: true });
/******/ 	};
/******/
/******/ 	// create a fake namespace object
/******/ 	// mode & 1: value is a module id, require it
/******/ 	// mode & 2: merge all properties of value into the ns
/******/ 	// mode & 4: return value when already ns object
/******/ 	// mode & 8|1: behave like require
/******/ 	__webpack_require__.t = function(value, mode) {
/******/ 		if(mode & 1) value = __webpack_require__(value);
/******/ 		if(mode & 8) return value;
/******/ 		if((mode & 4) && typeof value === 'object' && value && value.__esModule) return value;
/******/ 		var ns = Object.create(null);
/******/ 		__webpack_require__.r(ns);
/******/ 		Object.defineProperty(ns, 'default', { enumerable: true, value: value });
/******/ 		if(mode & 2 && typeof value != 'string') for(var key in value) __webpack_require__.d(ns, key, function(key) { return value[key]; }.bind(null, key));
/******/ 		return ns;
/******/ 	};
/******/
/******/ 	// getDefaultExport function for compatibility with non-harmony modules
/******/ 	__webpack_require__.n = function(module) {
/******/ 		var getter = module && module.__esModule ?
/******/ 			function getDefault() { return module['default']; } :
/******/ 			function getModuleExports() { return module; };
/******/ 		__webpack_require__.d(getter, 'a', getter);
/******/ 		return getter;
/******/ 	};
/******/
/******/ 	// Object.prototype.hasOwnProperty.call
/******/ 	__webpack_require__.o = function(object, property) { return Object.prototype.hasOwnProperty.call(object, property); };
/******/
/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";
/******/
/******/
/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(__webpack_require__.s = 0);
/******/ })
/************************************************************************/
/******/ ({

/***/ "./node_modules/@angular/router/router.ngfactory.js":
/*!**********************************************************!*\
  !*** ./node_modules/@angular/router/router.ngfactory.js ***!
  \**********************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var i0 = __webpack_require__(/*! @angular/core */ "@angular/core");
var i1 = __webpack_require__(/*! @angular/router */ "@angular/router");
var RouterModuleNgFactory = i0.ɵcmf(i1.RouterModule, [], function (_l) { return i0.ɵmod([i0.ɵmpd(512, i0.ComponentFactoryResolver, i0.ɵCodegenComponentFactoryResolver, [[8, [ɵEmptyOutletComponentNgFactory]], [3, i0.ComponentFactoryResolver], i0.NgModuleRef]), i0.ɵmpd(1073742336, i1.RouterModule, i1.RouterModule, [[2, i1.ɵangular_packages_router_router_a], [2, i1.Router]])]); });
exports.RouterModuleNgFactory = RouterModuleNgFactory;
var styles_ɵEmptyOutletComponent = [];
var RenderType_ɵEmptyOutletComponent = i0.ɵcrt({ encapsulation: 2, styles: styles_ɵEmptyOutletComponent, data: {} });
exports.RenderType_ɵEmptyOutletComponent = RenderType_ɵEmptyOutletComponent;
function View_ɵEmptyOutletComponent_0(_l) { return i0.ɵvid(0, [(_l()(), i0.ɵeld(0, 16777216, null, null, 1, "router-outlet", [], null, null, null, null, null)), i0.ɵdid(1, 212992, null, 0, i1.RouterOutlet, [i1.ChildrenOutletContexts, i0.ViewContainerRef, i0.ComponentFactoryResolver, [8, null], i0.ChangeDetectorRef], null, null)], function (_ck, _v) { _ck(_v, 1, 0); }, null); }
exports.View_ɵEmptyOutletComponent_0 = View_ɵEmptyOutletComponent_0;
function View_ɵEmptyOutletComponent_Host_0(_l) { return i0.ɵvid(0, [(_l()(), i0.ɵeld(0, 0, null, null, 1, "ng-component", [], null, null, null, View_ɵEmptyOutletComponent_0, RenderType_ɵEmptyOutletComponent)), i0.ɵdid(1, 49152, null, 0, i1.ɵEmptyOutletComponent, [], null, null)], null, null); }
exports.View_ɵEmptyOutletComponent_Host_0 = View_ɵEmptyOutletComponent_Host_0;
var ɵEmptyOutletComponentNgFactory = i0.ɵccf("ng-component", i1.ɵEmptyOutletComponent, View_ɵEmptyOutletComponent_Host_0, {}, {}, []);
exports.ɵEmptyOutletComponentNgFactory = ɵEmptyOutletComponentNgFactory;


/***/ }),

/***/ "./src/app/app-routing.module.ts":
/*!***************************************!*\
  !*** ./src/app/app-routing.module.ts ***!
  \***************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var router_1 = __webpack_require__(/*! @angular/router */ "@angular/router");
var home_component_1 = __webpack_require__(/*! ./pages/home/home.component */ "./src/app/pages/home/home.component.ts");
var about_component_1 = __webpack_require__(/*! ./pages/about/about.component */ "./src/app/pages/about/about.component.ts");
var services_component_1 = __webpack_require__(/*! ./pages/services/services.component */ "./src/app/pages/services/services.component.ts");
var contact_component_1 = __webpack_require__(/*! ./pages/contact/contact.component */ "./src/app/pages/contact/contact.component.ts");
var routes = [
    { path: 'home', component: home_component_1.HomeComponent },
    { path: 'about', component: about_component_1.AboutComponent },
    { path: 'services', component: services_component_1.ServicesComponent },
    { path: 'contact', component: contact_component_1.ContactComponent },
    { path: '**', redirectTo: '/home' },
];
var AppRoutingModule = /** @class */ (function () {
    function AppRoutingModule() {
    }
    return AppRoutingModule;
}());
exports.AppRoutingModule = AppRoutingModule;


/***/ }),

/***/ "./src/app/app.component.ngfactory.js":
/*!********************************************!*\
  !*** ./src/app/app.component.ngfactory.js ***!
  \********************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var i0 = __webpack_require__(/*! ./app.component.scss.shim.ngstyle */ "./src/app/app.component.scss.shim.ngstyle.js");
var i1 = __webpack_require__(/*! @angular/core */ "@angular/core");
var i2 = __webpack_require__(/*! ./components/toast/toast.component.ngfactory */ "./src/app/components/toast/toast.component.ngfactory.js");
var i3 = __webpack_require__(/*! ./components/toast/toast.component */ "./src/app/components/toast/toast.component.ts");
var i4 = __webpack_require__(/*! ./components/loading/loading.component.ngfactory */ "./src/app/components/loading/loading.component.ngfactory.js");
var i5 = __webpack_require__(/*! ./components/loading/loading.component */ "./src/app/components/loading/loading.component.ts");
var i6 = __webpack_require__(/*! ./components/nav-bar/nav-bar.component.ngfactory */ "./src/app/components/nav-bar/nav-bar.component.ngfactory.js");
var i7 = __webpack_require__(/*! ./components/nav-bar/nav-bar.component */ "./src/app/components/nav-bar/nav-bar.component.ts");
var i8 = __webpack_require__(/*! @angular/common */ "@angular/common");
var i9 = __webpack_require__(/*! @angular/router */ "@angular/router");
var i10 = __webpack_require__(/*! ./app.component */ "./src/app/app.component.ts");
var styles_AppComponent = [i0.styles];
var RenderType_AppComponent = i1.ɵcrt({ encapsulation: 0, styles: styles_AppComponent, data: {} });
exports.RenderType_AppComponent = RenderType_AppComponent;
function View_AppComponent_1(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "app-toast", [["class", "app-alert"]], null, null, null, i2.View_ToastComponent_0, i2.RenderType_ToastComponent)), i1.ɵdid(1, 114688, null, 0, i3.ToastComponent, [i1.Injector], null, null)], function (_ck, _v) { _ck(_v, 1, 0); }, null); }
function View_AppComponent_2(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "app-loading", [], null, null, null, i4.View_LoadingComponent_0, i4.RenderType_LoadingComponent)), i1.ɵdid(1, 114688, null, 0, i5.LoadingComponent, [], null, null)], function (_ck, _v) { _ck(_v, 1, 0); }, null); }
function View_AppComponent_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "nav-bar", [], null, null, null, i6.View_NavBarComponent_0, i6.RenderType_NavBarComponent)), i1.ɵdid(1, 114688, null, 0, i7.NavBarComponent, [], null, null), (_l()(), i1.ɵand(16777216, null, null, 1, null, View_AppComponent_1)), i1.ɵdid(3, 16384, null, 0, i8.NgIf, [i1.ViewContainerRef, i1.TemplateRef], { ngIf: [0, "ngIf"] }, null), (_l()(), i1.ɵand(16777216, null, null, 1, null, View_AppComponent_2)), i1.ɵdid(5, 16384, null, 0, i8.NgIf, [i1.ViewContainerRef, i1.TemplateRef], { ngIf: [0, "ngIf"] }, null), (_l()(), i1.ɵeld(6, 16777216, null, null, 1, "router-outlet", [], null, null, null, null, null)), i1.ɵdid(7, 212992, null, 0, i9.RouterOutlet, [i9.ChildrenOutletContexts, i1.ViewContainerRef, i1.ComponentFactoryResolver, [8, null], i1.ChangeDetectorRef], null, null)], function (_ck, _v) { var _co = _v.component; _ck(_v, 1, 0); var currVal_0 = _co.toastService.toastObj.isShow; _ck(_v, 3, 0, currVal_0); var currVal_1 = _co.loading; _ck(_v, 5, 0, currVal_1); _ck(_v, 7, 0); }, null); }
exports.View_AppComponent_0 = View_AppComponent_0;
function View_AppComponent_Host_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "app-root", [], null, null, null, View_AppComponent_0, RenderType_AppComponent)), i1.ɵdid(1, 49152, null, 0, i10.AppComponent, [i1.Injector], null, null)], null, null); }
exports.View_AppComponent_Host_0 = View_AppComponent_Host_0;
var AppComponentNgFactory = i1.ɵccf("app-root", i10.AppComponent, View_AppComponent_Host_0, {}, {}, []);
exports.AppComponentNgFactory = AppComponentNgFactory;


/***/ }),

/***/ "./src/app/app.component.scss.shim.ngstyle.js":
/*!****************************************************!*\
  !*** ./src/app/app.component.scss.shim.ngstyle.js ***!
  \****************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = [".app-alert[_ngcontent-%COMP%] {\n  position: absolute;\n  top: 43px;\n  width: 40%;\n  right: 0; }\n\n.black-box[_ngcontent-%COMP%] {\n  height: 100vh;\n  background-color: #ffb570; }\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi9Vc2Vycy90ZXN0L0Rlc2t0b3AvRGVtb19BcHBzL0FuZ3VsYXIgQXBwcy9naWdnYWRhL2dpZ2dhZGEvc3JjL2FwcC9hcHAuY29tcG9uZW50LnNjc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUE7RUFDSSxrQkFBa0I7RUFDbEIsU0FBUztFQUNULFVBQVU7RUFDVixRQUNKLEVBQUE7O0FBRUE7RUFDSSxhQUFhO0VBQ2IseUJBQW1DLEVBQUEiLCJmaWxlIjoic3JjL2FwcC9hcHAuY29tcG9uZW50LnNjc3MiLCJzb3VyY2VzQ29udGVudCI6WyIuYXBwLWFsZXJ0e1xuICAgIHBvc2l0aW9uOiBhYnNvbHV0ZTtcbiAgICB0b3A6IDQzcHg7XG4gICAgd2lkdGg6IDQwJTtcbiAgICByaWdodDogMFxufVxuXG4uYmxhY2stYm94e1xuICAgIGhlaWdodDogMTAwdmg7XG4gICAgYmFja2dyb3VuZC1jb2xvcjpyZ2IoMjU1LCAxODEsIDExMikgXG59Il19 */"];
exports.styles = styles;


/***/ }),

/***/ "./src/app/app.component.ts":
/*!**********************************!*\
  !*** ./src/app/app.component.ts ***!
  \**********************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var tslib_1 = __webpack_require__(/*! tslib */ "tslib");
var core_1 = __webpack_require__(/*! @angular/core */ "@angular/core");
var base_app_1 = __webpack_require__(/*! ./common/base-app */ "./src/app/common/base-app.ts");
var AppComponent = /** @class */ (function (_super) {
    tslib_1.__extends(AppComponent, _super);
    function AppComponent(injector) {
        var _this = _super.call(this, injector) || this;
        _this.injector = injector;
        _this.title = 'NgBaseLine';
        return _this;
    }
    return AppComponent;
}(base_app_1.BaseApp));
exports.AppComponent = AppComponent;


/***/ }),

/***/ "./src/app/app.module.ts":
/*!*******************************!*\
  !*** ./src/app/app.module.ts ***!
  \*******************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var AppModule = /** @class */ (function () {
    function AppModule() {
    }
    return AppModule;
}());
exports.AppModule = AppModule;


/***/ }),

/***/ "./src/app/app.server.module.ngfactory.js":
/*!************************************************!*\
  !*** ./src/app/app.server.module.ngfactory.js ***!
  \************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var i0 = __webpack_require__(/*! @angular/core */ "@angular/core");
var i1 = __webpack_require__(/*! ./app.server.module */ "./src/app/app.server.module.ts");
var i2 = __webpack_require__(/*! ./app.component */ "./src/app/app.component.ts");
var i3 = __webpack_require__(/*! ../../node_modules/@angular/router/router.ngfactory */ "./node_modules/@angular/router/router.ngfactory.js");
var i4 = __webpack_require__(/*! ./pages/home/home.component.ngfactory */ "./src/app/pages/home/home.component.ngfactory.js");
var i5 = __webpack_require__(/*! ./pages/about/about.component.ngfactory */ "./src/app/pages/about/about.component.ngfactory.js");
var i6 = __webpack_require__(/*! ./pages/services/services.component.ngfactory */ "./src/app/pages/services/services.component.ngfactory.js");
var i7 = __webpack_require__(/*! ./pages/contact/contact.component.ngfactory */ "./src/app/pages/contact/contact.component.ngfactory.js");
var i8 = __webpack_require__(/*! ./app.component.ngfactory */ "./src/app/app.component.ngfactory.js");
var i9 = __webpack_require__(/*! @angular/common */ "@angular/common");
var i10 = __webpack_require__(/*! @angular/platform-browser */ "@angular/platform-browser");
var i11 = __webpack_require__(/*! @angular/platform-server */ "@angular/platform-server");
var i12 = __webpack_require__(/*! @angular/animations/browser */ "@angular/animations/browser");
var i13 = __webpack_require__(/*! @angular/platform-browser/animations */ "@angular/platform-browser/animations");
var i14 = __webpack_require__(/*! @angular/router */ "@angular/router");
var i15 = __webpack_require__(/*! @angular/forms */ "@angular/forms");
var i16 = __webpack_require__(/*! @angular/common/http */ "@angular/common/http");
var i17 = __webpack_require__(/*! ./services/http-service/interceptor */ "./src/app/services/http-service/interceptor.ts");
var i18 = __webpack_require__(/*! @angular/http */ "@angular/http");
var i19 = __webpack_require__(/*! @angular/animations */ "@angular/animations");
var i20 = __webpack_require__(/*! @nguniversal/module-map-ngfactory-loader */ "@nguniversal/module-map-ngfactory-loader");
var i21 = __webpack_require__(/*! ./pages/home/home.component */ "./src/app/pages/home/home.component.ts");
var i22 = __webpack_require__(/*! ./pages/about/about.component */ "./src/app/pages/about/about.component.ts");
var i23 = __webpack_require__(/*! ./pages/services/services.component */ "./src/app/pages/services/services.component.ts");
var i24 = __webpack_require__(/*! ./pages/contact/contact.component */ "./src/app/pages/contact/contact.component.ts");
var i25 = __webpack_require__(/*! ./app-routing.module */ "./src/app/app-routing.module.ts");
var i26 = __webpack_require__(/*! ./app.module */ "./src/app/app.module.ts");
var AppServerModuleNgFactory = i0.ɵcmf(i1.AppServerModule, [i2.AppComponent], function (_l) { return i0.ɵmod([i0.ɵmpd(512, i0.ComponentFactoryResolver, i0.ɵCodegenComponentFactoryResolver, [[8, [i3.ɵEmptyOutletComponentNgFactory, i4.HomeComponentNgFactory, i5.AboutComponentNgFactory, i6.ServicesComponentNgFactory, i7.ContactComponentNgFactory, i8.AppComponentNgFactory]], [3, i0.ComponentFactoryResolver], i0.NgModuleRef]), i0.ɵmpd(5120, i0.LOCALE_ID, i0.ɵangular_packages_core_core_r, [[3, i0.LOCALE_ID]]), i0.ɵmpd(4608, i9.NgLocalization, i9.NgLocaleLocalization, [i0.LOCALE_ID, [2, i9.ɵangular_packages_common_common_a]]), i0.ɵmpd(5120, i0.IterableDiffers, i0.ɵangular_packages_core_core_p, []), i0.ɵmpd(5120, i0.KeyValueDiffers, i0.ɵangular_packages_core_core_q, []), i0.ɵmpd(4608, i10.DomSanitizer, i10.ɵDomSanitizerImpl, [i9.DOCUMENT]), i0.ɵmpd(6144, i0.Sanitizer, null, [i10.DomSanitizer]), i0.ɵmpd(4608, i10.HAMMER_GESTURE_CONFIG, i10.HammerGestureConfig, []), i0.ɵmpd(5120, i10.EVENT_MANAGER_PLUGINS, function (p0_0, p0_1, p0_2, p1_0, p2_0, p2_1, p2_2, p2_3, p3_0) { return [new i10.ɵDomEventsPlugin(p0_0, p0_1, p0_2), new i10.ɵKeyEventsPlugin(p1_0), new i10.ɵHammerGesturesPlugin(p2_0, p2_1, p2_2, p2_3), new i11.ɵangular_packages_platform_server_platform_server_d(p3_0)]; }, [i9.DOCUMENT, i0.NgZone, i0.PLATFORM_ID, i9.DOCUMENT, i9.DOCUMENT, i10.HAMMER_GESTURE_CONFIG, i0.ɵConsole, [2, i10.HAMMER_LOADER], i10.DOCUMENT]), i0.ɵmpd(4608, i10.EventManager, i10.EventManager, [i10.EVENT_MANAGER_PLUGINS, i0.NgZone]), i0.ɵmpd(135680, i10.ɵDomSharedStylesHost, i10.ɵDomSharedStylesHost, [i9.DOCUMENT]), i0.ɵmpd(4608, i10.ɵDomRendererFactory2, i10.ɵDomRendererFactory2, [i10.EventManager, i10.ɵDomSharedStylesHost]), i0.ɵmpd(4608, i11.ɵangular_packages_platform_server_platform_server_c, i11.ɵangular_packages_platform_server_platform_server_c, [i10.DOCUMENT, [2, i10.ɵTRANSITION_ID]]), i0.ɵmpd(6144, i10.ɵSharedStylesHost, null, [i11.ɵangular_packages_platform_server_platform_server_c]), i0.ɵmpd(4608, i11.ɵServerRendererFactory2, i11.ɵServerRendererFactory2, [i10.EventManager, i0.NgZone, i10.DOCUMENT, i10.ɵSharedStylesHost]), i0.ɵmpd(4608, i12.AnimationDriver, i12.ɵNoopAnimationDriver, []), i0.ɵmpd(5120, i12.ɵAnimationStyleNormalizer, i13.ɵangular_packages_platform_browser_animations_animations_b, []), i0.ɵmpd(4608, i12.ɵAnimationEngine, i13.ɵInjectableAnimationEngine, [i9.DOCUMENT, i12.AnimationDriver, i12.ɵAnimationStyleNormalizer]), i0.ɵmpd(5120, i0.RendererFactory2, i11.ɵangular_packages_platform_server_platform_server_a, [i11.ɵServerRendererFactory2, i12.ɵAnimationEngine, i0.NgZone]), i0.ɵmpd(4352, i0.Testability, null, []), i0.ɵmpd(5120, i14.ActivatedRoute, i14.ɵangular_packages_router_router_g, [i14.Router]), i0.ɵmpd(4608, i14.NoPreloading, i14.NoPreloading, []), i0.ɵmpd(6144, i14.PreloadingStrategy, null, [i14.NoPreloading]), i0.ɵmpd(135680, i14.RouterPreloader, i14.RouterPreloader, [i14.Router, i0.NgModuleFactoryLoader, i0.Compiler, i0.Injector, i14.PreloadingStrategy]), i0.ɵmpd(4608, i14.PreloadAllModules, i14.PreloadAllModules, []), i0.ɵmpd(4608, i9.ViewportScroller, i9.ɵNullViewportScroller, []), i0.ɵmpd(5120, i14.ɵangular_packages_router_router_n, i14.ɵangular_packages_router_router_c, [i14.Router, i9.ViewportScroller, i14.ROUTER_CONFIGURATION]), i0.ɵmpd(5120, i14.ROUTER_INITIALIZER, i14.ɵangular_packages_router_router_j, [i14.ɵangular_packages_router_router_h]), i0.ɵmpd(5120, i0.APP_BOOTSTRAP_LISTENER, function (p0_0) { return [p0_0]; }, [i14.ROUTER_INITIALIZER]), i0.ɵmpd(4608, i15.ɵangular_packages_forms_forms_j, i15.ɵangular_packages_forms_forms_j, []), i0.ɵmpd(4608, i16.HttpXsrfTokenExtractor, i16.ɵangular_packages_common_http_http_g, [i9.DOCUMENT, i0.PLATFORM_ID, i16.ɵangular_packages_common_http_http_e]), i0.ɵmpd(4608, i16.ɵangular_packages_common_http_http_h, i16.ɵangular_packages_common_http_http_h, [i16.HttpXsrfTokenExtractor, i16.ɵangular_packages_common_http_http_f]), i0.ɵmpd(5120, i16.HTTP_INTERCEPTORS, function (p0_0, p1_0) { return [p0_0, new i17.Interceptor(p1_0)]; }, [i16.ɵangular_packages_common_http_http_h, i0.Injector]), i0.ɵmpd(4608, i16.XhrFactory, i11.ɵangular_packages_platform_server_platform_server_e, []), i0.ɵmpd(4608, i16.HttpXhrBackend, i16.HttpXhrBackend, [i16.XhrFactory]), i0.ɵmpd(6144, i16.HttpBackend, null, [i16.HttpXhrBackend]), i0.ɵmpd(5120, i16.HttpHandler, i11.ɵangular_packages_platform_server_platform_server_h, [i16.HttpBackend, i0.Injector]), i0.ɵmpd(4608, i16.HttpClient, i16.HttpClient, [i16.HttpHandler]), i0.ɵmpd(4608, i16.ɵangular_packages_common_http_http_d, i16.ɵangular_packages_common_http_http_d, []), i0.ɵmpd(4608, i18.BrowserXhr, i11.ɵangular_packages_platform_server_platform_server_e, []), i0.ɵmpd(4608, i18.ResponseOptions, i18.BaseResponseOptions, []), i0.ɵmpd(4608, i18.XSRFStrategy, i11.ɵangular_packages_platform_server_platform_server_f, []), i0.ɵmpd(4608, i18.XHRBackend, i18.XHRBackend, [i18.BrowserXhr, i18.ResponseOptions, i18.XSRFStrategy]), i0.ɵmpd(4608, i18.RequestOptions, i18.BaseRequestOptions, []), i0.ɵmpd(5120, i18.Http, i11.ɵangular_packages_platform_server_platform_server_g, [i18.XHRBackend, i18.RequestOptions]), i0.ɵmpd(4608, i19.AnimationBuilder, i13.ɵBrowserAnimationBuilder, [i0.RendererFactory2, i10.DOCUMENT]), i0.ɵmpd(1073742336, i9.CommonModule, i9.CommonModule, []), i0.ɵmpd(1024, i0.ErrorHandler, i10.ɵangular_packages_platform_browser_platform_browser_a, []), i0.ɵmpd(1024, i0.NgProbeToken, function () { return [i14.ɵangular_packages_router_router_b()]; }, []), i0.ɵmpd(512, i14.ɵangular_packages_router_router_h, i14.ɵangular_packages_router_router_h, [i0.Injector]), i0.ɵmpd(256, i0.APP_ID, "Giggada", []), i0.ɵmpd(2048, i10.ɵTRANSITION_ID, null, [i0.APP_ID]), i0.ɵmpd(1024, i0.APP_INITIALIZER, function (p0_0, p1_0, p2_0, p2_1, p2_2) { return [i10.ɵangular_packages_platform_browser_platform_browser_j(p0_0), i14.ɵangular_packages_router_router_i(p1_0), i10.ɵangular_packages_platform_browser_platform_browser_h(p2_0, p2_1, p2_2)]; }, [[2, i0.NgProbeToken], i14.ɵangular_packages_router_router_h, i10.ɵTRANSITION_ID, i9.DOCUMENT, i0.Injector]), i0.ɵmpd(512, i0.ApplicationInitStatus, i0.ApplicationInitStatus, [[2, i0.APP_INITIALIZER]]), i0.ɵmpd(131584, i0.ApplicationRef, i0.ApplicationRef, [i0.NgZone, i0.ɵConsole, i0.Injector, i0.ErrorHandler, i0.ComponentFactoryResolver, i0.ApplicationInitStatus]), i0.ɵmpd(1073742336, i0.ApplicationModule, i0.ApplicationModule, [i0.ApplicationRef]), i0.ɵmpd(1073742336, i10.BrowserModule, i10.BrowserModule, [[3, i10.BrowserModule]]), i0.ɵmpd(1024, i14.ɵangular_packages_router_router_a, i14.ɵangular_packages_router_router_e, [[3, i14.Router]]), i0.ɵmpd(512, i14.UrlSerializer, i14.DefaultUrlSerializer, []), i0.ɵmpd(512, i14.ChildrenOutletContexts, i14.ChildrenOutletContexts, []), i0.ɵmpd(256, i14.ROUTER_CONFIGURATION, { useHash: false }, []), i0.ɵmpd(1024, i9.LocationStrategy, i14.ɵangular_packages_router_router_d, [i9.PlatformLocation, [2, i9.APP_BASE_HREF], i14.ROUTER_CONFIGURATION]), i0.ɵmpd(512, i9.Location, i9.Location, [i9.LocationStrategy]), i0.ɵmpd(512, i0.Compiler, i0.Compiler, []), i0.ɵmpd(512, i0.NgModuleFactoryLoader, i20.ModuleMapNgFactoryLoader, [i0.Compiler, i20.MODULE_MAP]), i0.ɵmpd(1024, i14.ROUTES, function () { return [[{ path: "home", component: i21.HomeComponent }, { path: "about", component: i22.AboutComponent }, { path: "services", component: i23.ServicesComponent }, { path: "contact", component: i24.ContactComponent }, { path: "**", redirectTo: "/home" }]]; }, []), i0.ɵmpd(1024, i14.Router, i14.ɵangular_packages_router_router_f, [i0.ApplicationRef, i14.UrlSerializer, i14.ChildrenOutletContexts, i9.Location, i0.Injector, i0.NgModuleFactoryLoader, i0.Compiler, i14.ROUTES, i14.ROUTER_CONFIGURATION, [2, i14.UrlHandlingStrategy], [2, i14.RouteReuseStrategy]]), i0.ɵmpd(1073742336, i14.RouterModule, i14.RouterModule, [[2, i14.ɵangular_packages_router_router_a], [2, i14.Router]]), i0.ɵmpd(1073742336, i25.AppRoutingModule, i25.AppRoutingModule, []), i0.ɵmpd(1073742336, i15.ɵangular_packages_forms_forms_bc, i15.ɵangular_packages_forms_forms_bc, []), i0.ɵmpd(1073742336, i15.FormsModule, i15.FormsModule, []), i0.ɵmpd(1073742336, i16.HttpClientXsrfModule, i16.HttpClientXsrfModule, []), i0.ɵmpd(1073742336, i16.HttpClientModule, i16.HttpClientModule, []), i0.ɵmpd(1073742336, i26.AppModule, i26.AppModule, []), i0.ɵmpd(1073742336, i18.HttpModule, i18.HttpModule, []), i0.ɵmpd(1073742336, i13.NoopAnimationsModule, i13.NoopAnimationsModule, []), i0.ɵmpd(1073742336, i11.ServerModule, i11.ServerModule, []), i0.ɵmpd(1073742336, i20.ModuleMapLoaderModule, i20.ModuleMapLoaderModule, []), i0.ɵmpd(1073742336, i1.AppServerModule, i1.AppServerModule, []), i0.ɵmpd(256, i0.ɵAPP_ROOT, true, []), i0.ɵmpd(256, i16.ɵangular_packages_common_http_http_e, "XSRF-TOKEN", []), i0.ɵmpd(256, i16.ɵangular_packages_common_http_http_f, "X-XSRF-TOKEN", []), i0.ɵmpd(256, i13.ANIMATION_MODULE_TYPE, "NoopAnimations", [])]); });
exports.AppServerModuleNgFactory = AppServerModuleNgFactory;


/***/ }),

/***/ "./src/app/app.server.module.ts":
/*!**************************************!*\
  !*** ./src/app/app.server.module.ts ***!
  \**************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var AppServerModule = /** @class */ (function () {
    function AppServerModule() {
    }
    return AppServerModule;
}());
exports.AppServerModule = AppServerModule;


/***/ }),

/***/ "./src/app/common/base-app.ts":
/*!************************************!*\
  !*** ./src/app/common/base-app.ts ***!
  \************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var APP_CONSTANTS = __webpack_require__(/*! ./constants */ "./src/app/common/constants.ts");
var session_service_1 = __webpack_require__(/*! ../services/session.service */ "./src/app/services/session.service.ts");
var event_service_1 = __webpack_require__(/*! ../services/event.service */ "./src/app/services/event.service.ts");
var cache_service_1 = __webpack_require__(/*! ../services/cache.service */ "./src/app/services/cache.service.ts");
var toast_service_1 = __webpack_require__(/*! ../services/toast.service */ "./src/app/services/toast.service.ts");
var BaseApp = /** @class */ (function () {
    function BaseApp(injector) {
        this.loading = false;
        this.CONSTANTS = APP_CONSTANTS;
        this.session = injector.get(session_service_1.SessionService);
        this.events = injector.get(event_service_1.EventService);
        this.cache = injector.get(cache_service_1.CacheService);
        this.toastService = injector.get(toast_service_1.ToastService);
    }
    BaseApp.prototype.presentLoading = function () {
        var _this = this;
        this.loading = true;
        setTimeout(function () {
            _this.loading = false;
        }, 3000);
    };
    BaseApp.prototype.dismissLoading = function () {
        this.loading = false;
    };
    return BaseApp;
}());
exports.BaseApp = BaseApp;


/***/ }),

/***/ "./src/app/common/constants.ts":
/*!*************************************!*\
  !*** ./src/app/common/constants.ts ***!
  \*************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
exports.USER = "user";
exports.EVENT = "event";
// cache keys
exports.CACHE_USER = "user";


/***/ }),

/***/ "./src/app/components/loading/loading.component.ngfactory.js":
/*!*******************************************************************!*\
  !*** ./src/app/components/loading/loading.component.ngfactory.js ***!
  \*******************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var i0 = __webpack_require__(/*! ./loading.component.scss.shim.ngstyle */ "./src/app/components/loading/loading.component.scss.shim.ngstyle.js");
var i1 = __webpack_require__(/*! @angular/core */ "@angular/core");
var i2 = __webpack_require__(/*! ./loading.component */ "./src/app/components/loading/loading.component.ts");
var styles_LoadingComponent = [i0.styles];
var RenderType_LoadingComponent = i1.ɵcrt({ encapsulation: 0, styles: styles_LoadingComponent, data: {} });
exports.RenderType_LoadingComponent = RenderType_LoadingComponent;
function View_LoadingComponent_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 2, "div", [["class", "loading"]], null, null, null, null, null)), (_l()(), i1.ɵeld(1, 0, null, null, 1, "div", [["class", " text-white d-inline-block loading-circle"]], null, null, null, null, null)), (_l()(), i1.ɵeld(2, 0, null, null, 0, "img", [["alt", ""], ["src", "../../../assets/imgs/loading.svg"]], null, null, null, null, null))], null, null); }
exports.View_LoadingComponent_0 = View_LoadingComponent_0;
function View_LoadingComponent_Host_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "app-loading", [], null, null, null, View_LoadingComponent_0, RenderType_LoadingComponent)), i1.ɵdid(1, 114688, null, 0, i2.LoadingComponent, [], null, null)], function (_ck, _v) { _ck(_v, 1, 0); }, null); }
exports.View_LoadingComponent_Host_0 = View_LoadingComponent_Host_0;
var LoadingComponentNgFactory = i1.ɵccf("app-loading", i2.LoadingComponent, View_LoadingComponent_Host_0, {}, {}, []);
exports.LoadingComponentNgFactory = LoadingComponentNgFactory;


/***/ }),

/***/ "./src/app/components/loading/loading.component.scss.shim.ngstyle.js":
/*!***************************************************************************!*\
  !*** ./src/app/components/loading/loading.component.scss.shim.ngstyle.js ***!
  \***************************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = [".loading[_ngcontent-%COMP%] {\n  background-color: #00000085;\n  position: absolute;\n  top: 0;\n  left: 0;\n  height: 100%;\n  width: 100%;\n  text-align: center; }\n\n.loading-circle[_ngcontent-%COMP%] {\n  margin-top: 25%; }\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi9Vc2Vycy90ZXN0L0Rlc2t0b3AvRGVtb19BcHBzL0FuZ3VsYXIgQXBwcy9naWdnYWRhL2dpZ2dhZGEvc3JjL2FwcC9jb21wb25lbnRzL2xvYWRpbmcvbG9hZGluZy5jb21wb25lbnQuc2NzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBQTtFQUNJLDJCQUEyQjtFQUMzQixrQkFBa0I7RUFDbEIsTUFBTTtFQUNOLE9BQU87RUFDUCxZQUFZO0VBQ1osV0FBVztFQUNYLGtCQUNKLEVBQUE7O0FBRUE7RUFDSSxlQUFlLEVBQUEiLCJmaWxlIjoic3JjL2FwcC9jb21wb25lbnRzL2xvYWRpbmcvbG9hZGluZy5jb21wb25lbnQuc2NzcyIsInNvdXJjZXNDb250ZW50IjpbIi5sb2FkaW5ne1xuICAgIGJhY2tncm91bmQtY29sb3I6ICMwMDAwMDA4NTtcbiAgICBwb3NpdGlvbjogYWJzb2x1dGU7XG4gICAgdG9wOiAwO1xuICAgIGxlZnQ6IDA7XG4gICAgaGVpZ2h0OiAxMDAlO1xuICAgIHdpZHRoOiAxMDAlO1xuICAgIHRleHQtYWxpZ246IGNlbnRlclxufVxuXG4ubG9hZGluZy1jaXJjbGV7XG4gICAgbWFyZ2luLXRvcDogMjUlO1xufSJdfQ== */"];
exports.styles = styles;


/***/ }),

/***/ "./src/app/components/loading/loading.component.ts":
/*!*********************************************************!*\
  !*** ./src/app/components/loading/loading.component.ts ***!
  \*********************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var core_1 = __webpack_require__(/*! @angular/core */ "@angular/core");
var LoadingComponent = /** @class */ (function () {
    function LoadingComponent() {
    }
    LoadingComponent.prototype.ngOnInit = function () {
    };
    return LoadingComponent;
}());
exports.LoadingComponent = LoadingComponent;


/***/ }),

/***/ "./src/app/components/nav-bar/nav-bar.component.ngfactory.js":
/*!*******************************************************************!*\
  !*** ./src/app/components/nav-bar/nav-bar.component.ngfactory.js ***!
  \*******************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var i0 = __webpack_require__(/*! ./nav-bar.component.scss.shim.ngstyle */ "./src/app/components/nav-bar/nav-bar.component.scss.shim.ngstyle.js");
var i1 = __webpack_require__(/*! @angular/core */ "@angular/core");
var i2 = __webpack_require__(/*! @angular/router */ "@angular/router");
var i3 = __webpack_require__(/*! ./nav-bar.component */ "./src/app/components/nav-bar/nav-bar.component.ts");
var styles_NavBarComponent = [i0.styles];
var RenderType_NavBarComponent = i1.ɵcrt({ encapsulation: 0, styles: styles_NavBarComponent, data: {} });
exports.RenderType_NavBarComponent = RenderType_NavBarComponent;
function View_NavBarComponent_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 39, "nav", [["class", "navbar navbar-expand-lg navbar-dark bg-dark text-light"]], null, null, null, null, null)), (_l()(), i1.ɵeld(1, 0, null, null, 38, "div", [["class", "container"]], null, null, null, null, null)), (_l()(), i1.ɵeld(2, 0, null, null, 1, "a", [["class", "navbar-brand"], ["href", "#"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["ERP Tech"])), (_l()(), i1.ɵeld(4, 0, null, null, 1, "button", [["aria-controls", "navbarSupportedContent"], ["aria-expanded", "false"], ["aria-label", "Toggle navigation"], ["class", "navbar-toggler"], ["data-target", "#navbarSupportedContent"], ["data-toggle", "collapse"], ["type", "button"]], null, null, null, null, null)), (_l()(), i1.ɵeld(5, 0, null, null, 0, "span", [["class", "navbar-toggler-icon"]], null, null, null, null, null)), (_l()(), i1.ɵeld(6, 0, null, null, 33, "div", [["class", "collapse navbar-collapse"], ["id", "navbarSupportedContent"]], null, null, null, null, null)), (_l()(), i1.ɵeld(7, 0, null, null, 32, "ul", [["class", "navbar-nav ml-auto"]], null, null, null, null, null)), (_l()(), i1.ɵeld(8, 0, null, null, 7, "li", [["class", "nav-item"], ["routerLinkActive", "active"]], null, [[null, "click"]], function (_v, en, $event) { var ad = true; if (("click" === en)) {
        var pd_0 = (i1.ɵnov(_v, 9).onClick() !== false);
        ad = (pd_0 && ad);
    } return ad; }, null, null)), i1.ɵdid(9, 16384, [[1, 4]], 0, i2.RouterLink, [i2.Router, i2.ActivatedRoute, [8, null], i1.Renderer2, i1.ElementRef], { routerLink: [0, "routerLink"] }, null), i1.ɵpad(10, 1), i1.ɵdid(11, 1720320, null, 2, i2.RouterLinkActive, [i2.Router, i1.ElementRef, i1.Renderer2, i1.ChangeDetectorRef], { routerLinkActive: [0, "routerLinkActive"] }, null), i1.ɵqud(603979776, 1, { links: 1 }), i1.ɵqud(603979776, 2, { linksWithHrefs: 1 }), (_l()(), i1.ɵeld(14, 0, null, null, 1, "a", [["class", "nav-link"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Home"])), (_l()(), i1.ɵeld(16, 0, null, null, 7, "li", [["class", "nav-item"], ["routerLinkActive", "active"]], null, [[null, "click"]], function (_v, en, $event) { var ad = true; if (("click" === en)) {
        var pd_0 = (i1.ɵnov(_v, 17).onClick() !== false);
        ad = (pd_0 && ad);
    } return ad; }, null, null)), i1.ɵdid(17, 16384, [[3, 4]], 0, i2.RouterLink, [i2.Router, i2.ActivatedRoute, [8, null], i1.Renderer2, i1.ElementRef], { routerLink: [0, "routerLink"] }, null), i1.ɵpad(18, 1), i1.ɵdid(19, 1720320, null, 2, i2.RouterLinkActive, [i2.Router, i1.ElementRef, i1.Renderer2, i1.ChangeDetectorRef], { routerLinkActive: [0, "routerLinkActive"] }, null), i1.ɵqud(603979776, 3, { links: 1 }), i1.ɵqud(603979776, 4, { linksWithHrefs: 1 }), (_l()(), i1.ɵeld(22, 0, null, null, 1, "a", [["class", "nav-link"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["About"])), (_l()(), i1.ɵeld(24, 0, null, null, 7, "li", [["class", "nav-item"], ["routerLinkActive", "active"]], null, [[null, "click"]], function (_v, en, $event) { var ad = true; if (("click" === en)) {
        var pd_0 = (i1.ɵnov(_v, 25).onClick() !== false);
        ad = (pd_0 && ad);
    } return ad; }, null, null)), i1.ɵdid(25, 16384, [[5, 4]], 0, i2.RouterLink, [i2.Router, i2.ActivatedRoute, [8, null], i1.Renderer2, i1.ElementRef], { routerLink: [0, "routerLink"] }, null), i1.ɵpad(26, 1), i1.ɵdid(27, 1720320, null, 2, i2.RouterLinkActive, [i2.Router, i1.ElementRef, i1.Renderer2, i1.ChangeDetectorRef], { routerLinkActive: [0, "routerLinkActive"] }, null), i1.ɵqud(603979776, 5, { links: 1 }), i1.ɵqud(603979776, 6, { linksWithHrefs: 1 }), (_l()(), i1.ɵeld(30, 0, null, null, 1, "a", [["class", "nav-link"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Services"])), (_l()(), i1.ɵeld(32, 0, null, null, 7, "li", [["class", "nav-item"], ["routerLinkActive", "active"]], null, [[null, "click"]], function (_v, en, $event) { var ad = true; if (("click" === en)) {
        var pd_0 = (i1.ɵnov(_v, 33).onClick() !== false);
        ad = (pd_0 && ad);
    } return ad; }, null, null)), i1.ɵdid(33, 16384, [[7, 4]], 0, i2.RouterLink, [i2.Router, i2.ActivatedRoute, [8, null], i1.Renderer2, i1.ElementRef], { routerLink: [0, "routerLink"] }, null), i1.ɵpad(34, 1), i1.ɵdid(35, 1720320, null, 2, i2.RouterLinkActive, [i2.Router, i1.ElementRef, i1.Renderer2, i1.ChangeDetectorRef], { routerLinkActive: [0, "routerLinkActive"] }, null), i1.ɵqud(603979776, 7, { links: 1 }), i1.ɵqud(603979776, 8, { linksWithHrefs: 1 }), (_l()(), i1.ɵeld(38, 0, null, null, 1, "a", [["class", "nav-link"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Contact us"]))], function (_ck, _v) { var currVal_0 = _ck(_v, 10, 0, "/home"); _ck(_v, 9, 0, currVal_0); var currVal_1 = "active"; _ck(_v, 11, 0, currVal_1); var currVal_2 = _ck(_v, 18, 0, "/about"); _ck(_v, 17, 0, currVal_2); var currVal_3 = "active"; _ck(_v, 19, 0, currVal_3); var currVal_4 = _ck(_v, 26, 0, "/services"); _ck(_v, 25, 0, currVal_4); var currVal_5 = "active"; _ck(_v, 27, 0, currVal_5); var currVal_6 = _ck(_v, 34, 0, "/contact"); _ck(_v, 33, 0, currVal_6); var currVal_7 = "active"; _ck(_v, 35, 0, currVal_7); }, null); }
exports.View_NavBarComponent_0 = View_NavBarComponent_0;
function View_NavBarComponent_Host_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "nav-bar", [], null, null, null, View_NavBarComponent_0, RenderType_NavBarComponent)), i1.ɵdid(1, 114688, null, 0, i3.NavBarComponent, [], null, null)], function (_ck, _v) { _ck(_v, 1, 0); }, null); }
exports.View_NavBarComponent_Host_0 = View_NavBarComponent_Host_0;
var NavBarComponentNgFactory = i1.ɵccf("nav-bar", i3.NavBarComponent, View_NavBarComponent_Host_0, {}, {}, []);
exports.NavBarComponentNgFactory = NavBarComponentNgFactory;


/***/ }),

/***/ "./src/app/components/nav-bar/nav-bar.component.scss.shim.ngstyle.js":
/*!***************************************************************************!*\
  !*** ./src/app/components/nav-bar/nav-bar.component.scss.shim.ngstyle.js ***!
  \***************************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = ["\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiIsImZpbGUiOiJzcmMvYXBwL2NvbXBvbmVudHMvbmF2LWJhci9uYXYtYmFyLmNvbXBvbmVudC5zY3NzIn0= */"];
exports.styles = styles;


/***/ }),

/***/ "./src/app/components/nav-bar/nav-bar.component.ts":
/*!*********************************************************!*\
  !*** ./src/app/components/nav-bar/nav-bar.component.ts ***!
  \*********************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var core_1 = __webpack_require__(/*! @angular/core */ "@angular/core");
var NavBarComponent = /** @class */ (function () {
    function NavBarComponent() {
    }
    NavBarComponent.prototype.ngOnInit = function () {
    };
    return NavBarComponent;
}());
exports.NavBarComponent = NavBarComponent;


/***/ }),

/***/ "./src/app/components/toast/toast.component.ngfactory.js":
/*!***************************************************************!*\
  !*** ./src/app/components/toast/toast.component.ngfactory.js ***!
  \***************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var i0 = __webpack_require__(/*! ./toast.component.scss.shim.ngstyle */ "./src/app/components/toast/toast.component.scss.shim.ngstyle.js");
var i1 = __webpack_require__(/*! @angular/core */ "@angular/core");
var i2 = __webpack_require__(/*! @angular/common */ "@angular/common");
var i3 = __webpack_require__(/*! ./toast.component */ "./src/app/components/toast/toast.component.ts");
var styles_ToastComponent = [i0.styles];
var RenderType_ToastComponent = i1.ɵcrt({ encapsulation: 0, styles: styles_ToastComponent, data: {} });
exports.RenderType_ToastComponent = RenderType_ToastComponent;
function View_ToastComponent_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 2, "div", [["class", "alert px-5 text-center alert-info"]], null, null, null, null, null)), i1.ɵdid(1, 278528, null, 0, i2.NgClass, [i1.IterableDiffers, i1.KeyValueDiffers, i1.ElementRef, i1.Renderer2], { klass: [0, "klass"], ngClass: [1, "ngClass"] }, null), (_l()(), i1.ɵted(2, null, ["", ""]))], function (_ck, _v) { var _co = _v.component; var currVal_0 = "alert px-5 text-center alert-info"; var currVal_1 = _co.toastService.toastObj.toastType; _ck(_v, 1, 0, currVal_0, currVal_1); }, function (_ck, _v) { var _co = _v.component; var currVal_2 = _co.toastService.toastObj.toastMsg; _ck(_v, 2, 0, currVal_2); }); }
exports.View_ToastComponent_0 = View_ToastComponent_0;
function View_ToastComponent_Host_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "app-toast", [], null, null, null, View_ToastComponent_0, RenderType_ToastComponent)), i1.ɵdid(1, 114688, null, 0, i3.ToastComponent, [i1.Injector], null, null)], function (_ck, _v) { _ck(_v, 1, 0); }, null); }
exports.View_ToastComponent_Host_0 = View_ToastComponent_Host_0;
var ToastComponentNgFactory = i1.ɵccf("app-toast", i3.ToastComponent, View_ToastComponent_Host_0, {}, {}, []);
exports.ToastComponentNgFactory = ToastComponentNgFactory;


/***/ }),

/***/ "./src/app/components/toast/toast.component.scss.shim.ngstyle.js":
/*!***********************************************************************!*\
  !*** ./src/app/components/toast/toast.component.scss.shim.ngstyle.js ***!
  \***********************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = ["\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiIsImZpbGUiOiJzcmMvYXBwL2NvbXBvbmVudHMvdG9hc3QvdG9hc3QuY29tcG9uZW50LnNjc3MifQ== */"];
exports.styles = styles;


/***/ }),

/***/ "./src/app/components/toast/toast.component.ts":
/*!*****************************************************!*\
  !*** ./src/app/components/toast/toast.component.ts ***!
  \*****************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var tslib_1 = __webpack_require__(/*! tslib */ "tslib");
var core_1 = __webpack_require__(/*! @angular/core */ "@angular/core");
var base_app_1 = __webpack_require__(/*! ../../common/base-app */ "./src/app/common/base-app.ts");
var ToastComponent = /** @class */ (function (_super) {
    tslib_1.__extends(ToastComponent, _super);
    function ToastComponent(injector) {
        return _super.call(this, injector) || this;
    }
    ToastComponent.prototype.ngOnInit = function () {
    };
    return ToastComponent;
}(base_app_1.BaseApp));
exports.ToastComponent = ToastComponent;


/***/ }),

/***/ "./src/app/pages/about/about.component.ngfactory.js":
/*!**********************************************************!*\
  !*** ./src/app/pages/about/about.component.ngfactory.js ***!
  \**********************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var i0 = __webpack_require__(/*! ./about.component.scss.shim.ngstyle */ "./src/app/pages/about/about.component.scss.shim.ngstyle.js");
var i1 = __webpack_require__(/*! @angular/core */ "@angular/core");
var i2 = __webpack_require__(/*! ./about.component */ "./src/app/pages/about/about.component.ts");
var styles_AboutComponent = [i0.styles];
var RenderType_AboutComponent = i1.ɵcrt({ encapsulation: 0, styles: styles_AboutComponent, data: {} });
exports.RenderType_AboutComponent = RenderType_AboutComponent;
function View_AboutComponent_0(_l) { return i1.ɵvid(0, [], null, null); }
exports.View_AboutComponent_0 = View_AboutComponent_0;
function View_AboutComponent_Host_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "app-about", [], null, null, null, View_AboutComponent_0, RenderType_AboutComponent)), i1.ɵdid(1, 114688, null, 0, i2.AboutComponent, [], null, null)], function (_ck, _v) { _ck(_v, 1, 0); }, null); }
exports.View_AboutComponent_Host_0 = View_AboutComponent_Host_0;
var AboutComponentNgFactory = i1.ɵccf("app-about", i2.AboutComponent, View_AboutComponent_Host_0, {}, {}, []);
exports.AboutComponentNgFactory = AboutComponentNgFactory;


/***/ }),

/***/ "./src/app/pages/about/about.component.scss.shim.ngstyle.js":
/*!******************************************************************!*\
  !*** ./src/app/pages/about/about.component.scss.shim.ngstyle.js ***!
  \******************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = ["\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiIsImZpbGUiOiJzcmMvYXBwL3BhZ2VzL2Fib3V0L2Fib3V0LmNvbXBvbmVudC5zY3NzIn0= */"];
exports.styles = styles;


/***/ }),

/***/ "./src/app/pages/about/about.component.ts":
/*!************************************************!*\
  !*** ./src/app/pages/about/about.component.ts ***!
  \************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var core_1 = __webpack_require__(/*! @angular/core */ "@angular/core");
var AboutComponent = /** @class */ (function () {
    function AboutComponent() {
    }
    AboutComponent.prototype.ngOnInit = function () {
    };
    return AboutComponent;
}());
exports.AboutComponent = AboutComponent;


/***/ }),

/***/ "./src/app/pages/contact/contact.component.ngfactory.js":
/*!**************************************************************!*\
  !*** ./src/app/pages/contact/contact.component.ngfactory.js ***!
  \**************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var i0 = __webpack_require__(/*! ./contact.component.scss.shim.ngstyle */ "./src/app/pages/contact/contact.component.scss.shim.ngstyle.js");
var i1 = __webpack_require__(/*! @angular/core */ "@angular/core");
var i2 = __webpack_require__(/*! @angular/forms */ "@angular/forms");
var i3 = __webpack_require__(/*! ./contact.component */ "./src/app/pages/contact/contact.component.ts");
var styles_ContactComponent = [i0.styles];
var RenderType_ContactComponent = i1.ɵcrt({ encapsulation: 0, styles: styles_ContactComponent, data: {} });
exports.RenderType_ContactComponent = RenderType_ContactComponent;
function View_ContactComponent_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 4, "header", [["class", "py-3"], ["id", "contact-header"]], null, null, null, null, null)), (_l()(), i1.ɵeld(1, 0, null, null, 3, "div", [["class", "container text-center"]], null, null, null, null, null)), (_l()(), i1.ɵeld(2, 0, null, null, 2, "h2", [], null, null, null, null, null)), (_l()(), i1.ɵeld(3, 0, null, null, 1, "u", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Get in Touch"])), (_l()(), i1.ɵeld(5, 0, null, null, 71, "section", [["id", "contact-body"]], null, null, null, null, null)), (_l()(), i1.ɵeld(6, 0, null, null, 70, "div", [["class", "container"]], null, null, null, null, null)), (_l()(), i1.ɵeld(7, 0, null, null, 69, "div", [["class", "row"]], null, null, null, null, null)), (_l()(), i1.ɵeld(8, 0, null, null, 40, "div", [["class", "col-md-6"]], null, null, null, null, null)), (_l()(), i1.ɵeld(9, 0, null, null, 19, "div", [["class", "mb-4"]], null, null, null, null, null)), (_l()(), i1.ɵeld(10, 0, null, null, 1, "h4", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Headquarters:"])), (_l()(), i1.ɵeld(12, 0, null, null, 1, "p", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["3rd Floor,Aryaprathm Ap, Above Fedral Bank, Near Leelawati College, Warje Pune 411058"])), (_l()(), i1.ɵeld(14, 0, null, null, 1, "b", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, [" Phone:"])), (_l()(), i1.ɵted(-1, null, [" +91 7276 677 444 "])), (_l()(), i1.ɵeld(17, 0, null, null, 0, "br", [], null, null, null, null, null)), (_l()(), i1.ɵeld(18, 0, null, null, 1, "b", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, [" Phone:"])), (_l()(), i1.ɵted(-1, null, [" +91 8087 987 444 "])), (_l()(), i1.ɵeld(21, 0, null, null, 0, "br", [], null, null, null, null, null)), (_l()(), i1.ɵeld(22, 0, null, null, 1, "b", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, [" Phone:"])), (_l()(), i1.ɵted(-1, null, [" +91 8087 765 444 "])), (_l()(), i1.ɵeld(25, 0, null, null, 0, "br", [], null, null, null, null, null)), (_l()(), i1.ɵeld(26, 0, null, null, 1, "b", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Email:"])), (_l()(), i1.ɵted(-1, null, [" info@giggada.com "])), (_l()(), i1.ɵeld(29, 0, null, null, 19, "div", [["class", "mb-4"]], null, null, null, null, null)), (_l()(), i1.ɵeld(30, 0, null, null, 1, "h4", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Branch Office:"])), (_l()(), i1.ɵeld(32, 0, null, null, 1, "p", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Vilasvishwa Apt,NDA Road, Shinde Bridge,Shivane, Pune-411023"])), (_l()(), i1.ɵeld(34, 0, null, null, 1, "b", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, [" Phone:"])), (_l()(), i1.ɵted(-1, null, [" +91 7276 677 444 "])), (_l()(), i1.ɵeld(37, 0, null, null, 0, "br", [], null, null, null, null, null)), (_l()(), i1.ɵeld(38, 0, null, null, 1, "b", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, [" Phone:"])), (_l()(), i1.ɵted(-1, null, [" +91 8087 987 444 "])), (_l()(), i1.ɵeld(41, 0, null, null, 0, "br", [], null, null, null, null, null)), (_l()(), i1.ɵeld(42, 0, null, null, 1, "b", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, [" Phone:"])), (_l()(), i1.ɵted(-1, null, [" +91 8087 765 444 "])), (_l()(), i1.ɵeld(45, 0, null, null, 0, "br", [], null, null, null, null, null)), (_l()(), i1.ɵeld(46, 0, null, null, 1, "b", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Email:"])), (_l()(), i1.ɵted(-1, null, [" info@giggada.com "])), (_l()(), i1.ɵeld(49, 0, null, null, 27, "div", [["class", "col-md-6"]], null, null, null, null, null)), (_l()(), i1.ɵeld(50, 0, null, null, 26, "div", [["class", "container"]], null, null, null, null, null)), (_l()(), i1.ɵeld(51, 0, null, null, 25, "div", [["class", "card"]], null, null, null, null, null)), (_l()(), i1.ɵeld(52, 0, null, null, 24, "div", [["class", "card-body bg-dark text-white"]], null, null, null, null, null)), (_l()(), i1.ɵeld(53, 0, null, null, 23, "form", [["novalidate", ""]], [[2, "ng-untouched", null], [2, "ng-touched", null], [2, "ng-pristine", null], [2, "ng-dirty", null], [2, "ng-valid", null], [2, "ng-invalid", null], [2, "ng-pending", null]], [[null, "submit"], [null, "reset"]], function (_v, en, $event) { var ad = true; if (("submit" === en)) {
        var pd_0 = (i1.ɵnov(_v, 55).onSubmit($event) !== false);
        ad = (pd_0 && ad);
    } if (("reset" === en)) {
        var pd_1 = (i1.ɵnov(_v, 55).onReset() !== false);
        ad = (pd_1 && ad);
    } return ad; }, null, null)), i1.ɵdid(54, 16384, null, 0, i2.ɵangular_packages_forms_forms_bh, [], null, null), i1.ɵdid(55, 4210688, null, 0, i2.NgForm, [[8, null], [8, null]], null, null), i1.ɵprd(2048, null, i2.ControlContainer, null, [i2.NgForm]), i1.ɵdid(57, 16384, null, 0, i2.NgControlStatusGroup, [[4, i2.ControlContainer]], null, null), (_l()(), i1.ɵeld(58, 0, null, null, 1, "div", [["class", "mb-2"]], null, null, null, null, null)), (_l()(), i1.ɵeld(59, 0, null, null, 0, "input", [["class", "form-control"], ["placeholder", "Name"], ["type", "text"]], null, null, null, null, null)), (_l()(), i1.ɵeld(60, 0, null, null, 5, "div", [["class", "mb-2"]], null, null, null, null, null)), (_l()(), i1.ɵeld(61, 0, null, null, 4, "div", [["class", "input-group "]], null, null, null, null, null)), (_l()(), i1.ɵeld(62, 0, null, null, 2, "div", [["class", "input-group-prepend"]], null, null, null, null, null)), (_l()(), i1.ɵeld(63, 0, null, null, 1, "span", [["class", "input-group-text"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["+91"])), (_l()(), i1.ɵeld(65, 0, null, null, 0, "input", [["class", "form-control"], ["maxlength", "10"], ["placeholder", "Mobile"], ["type", "number"]], null, null, null, null, null)), (_l()(), i1.ɵeld(66, 0, null, null, 5, "div", [["class", "mb-2"]], null, null, null, null, null)), (_l()(), i1.ɵeld(67, 0, null, null, 4, "div", [["class", "input-group "]], null, null, null, null, null)), (_l()(), i1.ɵeld(68, 0, null, null, 2, "div", [["class", "input-group-prepend"]], null, null, null, null, null)), (_l()(), i1.ɵeld(69, 0, null, null, 1, "span", [["class", "input-group-text"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["@"])), (_l()(), i1.ɵeld(71, 0, null, null, 0, "input", [["class", "form-control"], ["placeholder", "Email"], ["type", "text"]], null, null, null, null, null)), (_l()(), i1.ɵeld(72, 0, null, null, 1, "div", [["class", "input-group mb-2"]], null, null, null, null, null)), (_l()(), i1.ɵeld(73, 0, null, null, 0, "textarea", [["class", "form-control"], ["placeholder", "Message"], ["rows", "4"], ["type", "text"]], null, null, null, null, null)), (_l()(), i1.ɵeld(74, 0, null, null, 2, "a", [["class", "btn btn-block btn-primary btn-info"]], null, null, null, null, null)), (_l()(), i1.ɵeld(75, 0, null, null, 0, "span", [["class", "fa fa-send"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, [" Send Message"]))], null, function (_ck, _v) { var currVal_0 = i1.ɵnov(_v, 57).ngClassUntouched; var currVal_1 = i1.ɵnov(_v, 57).ngClassTouched; var currVal_2 = i1.ɵnov(_v, 57).ngClassPristine; var currVal_3 = i1.ɵnov(_v, 57).ngClassDirty; var currVal_4 = i1.ɵnov(_v, 57).ngClassValid; var currVal_5 = i1.ɵnov(_v, 57).ngClassInvalid; var currVal_6 = i1.ɵnov(_v, 57).ngClassPending; _ck(_v, 53, 0, currVal_0, currVal_1, currVal_2, currVal_3, currVal_4, currVal_5, currVal_6); }); }
exports.View_ContactComponent_0 = View_ContactComponent_0;
function View_ContactComponent_Host_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "app-contact", [], null, null, null, View_ContactComponent_0, RenderType_ContactComponent)), i1.ɵdid(1, 114688, null, 0, i3.ContactComponent, [], null, null)], function (_ck, _v) { _ck(_v, 1, 0); }, null); }
exports.View_ContactComponent_Host_0 = View_ContactComponent_Host_0;
var ContactComponentNgFactory = i1.ɵccf("app-contact", i3.ContactComponent, View_ContactComponent_Host_0, {}, {}, []);
exports.ContactComponentNgFactory = ContactComponentNgFactory;


/***/ }),

/***/ "./src/app/pages/contact/contact.component.scss.shim.ngstyle.js":
/*!**********************************************************************!*\
  !*** ./src/app/pages/contact/contact.component.scss.shim.ngstyle.js ***!
  \**********************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = ["\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiIsImZpbGUiOiJzcmMvYXBwL3BhZ2VzL2NvbnRhY3QvY29udGFjdC5jb21wb25lbnQuc2NzcyJ9 */"];
exports.styles = styles;


/***/ }),

/***/ "./src/app/pages/contact/contact.component.ts":
/*!****************************************************!*\
  !*** ./src/app/pages/contact/contact.component.ts ***!
  \****************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var core_1 = __webpack_require__(/*! @angular/core */ "@angular/core");
var ContactComponent = /** @class */ (function () {
    function ContactComponent() {
    }
    ContactComponent.prototype.ngOnInit = function () {
    };
    return ContactComponent;
}());
exports.ContactComponent = ContactComponent;


/***/ }),

/***/ "./src/app/pages/home/home.component.ngfactory.js":
/*!********************************************************!*\
  !*** ./src/app/pages/home/home.component.ngfactory.js ***!
  \********************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var i0 = __webpack_require__(/*! ./home.component.scss.shim.ngstyle */ "./src/app/pages/home/home.component.scss.shim.ngstyle.js");
var i1 = __webpack_require__(/*! @angular/core */ "@angular/core");
var i2 = __webpack_require__(/*! ./home.component */ "./src/app/pages/home/home.component.ts");
var styles_HomeComponent = [i0.styles];
var RenderType_HomeComponent = i1.ɵcrt({ encapsulation: 0, styles: styles_HomeComponent, data: {} });
exports.RenderType_HomeComponent = RenderType_HomeComponent;
function View_HomeComponent_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "p", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, [" home works!\n"]))], null, null); }
exports.View_HomeComponent_0 = View_HomeComponent_0;
function View_HomeComponent_Host_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "app-home", [], null, null, null, View_HomeComponent_0, RenderType_HomeComponent)), i1.ɵdid(1, 114688, null, 0, i2.HomeComponent, [i1.Injector], null, null)], function (_ck, _v) { _ck(_v, 1, 0); }, null); }
exports.View_HomeComponent_Host_0 = View_HomeComponent_Host_0;
var HomeComponentNgFactory = i1.ɵccf("app-home", i2.HomeComponent, View_HomeComponent_Host_0, {}, {}, []);
exports.HomeComponentNgFactory = HomeComponentNgFactory;


/***/ }),

/***/ "./src/app/pages/home/home.component.scss.shim.ngstyle.js":
/*!****************************************************************!*\
  !*** ./src/app/pages/home/home.component.scss.shim.ngstyle.js ***!
  \****************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = ["\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiIsImZpbGUiOiJzcmMvYXBwL3BhZ2VzL2hvbWUvaG9tZS5jb21wb25lbnQuc2NzcyJ9 */"];
exports.styles = styles;


/***/ }),

/***/ "./src/app/pages/home/home.component.ts":
/*!**********************************************!*\
  !*** ./src/app/pages/home/home.component.ts ***!
  \**********************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var tslib_1 = __webpack_require__(/*! tslib */ "tslib");
var core_1 = __webpack_require__(/*! @angular/core */ "@angular/core");
var base_app_1 = __webpack_require__(/*! ../../common/base-app */ "./src/app/common/base-app.ts");
var HomeComponent = /** @class */ (function (_super) {
    tslib_1.__extends(HomeComponent, _super);
    function HomeComponent(injector) {
        var _this = _super.call(this, injector) || this;
        _this.injector = injector;
        _this.events.loginEvent.emit('login called');
        return _this;
    }
    HomeComponent.prototype.ngOnInit = function () {
        this.events.loginEvent.emit(true);
        if (this.session.userLoggedIn) {
            console.log('user is ', true);
        }
    };
    return HomeComponent;
}(base_app_1.BaseApp));
exports.HomeComponent = HomeComponent;


/***/ }),

/***/ "./src/app/pages/services/services.component.ngfactory.js":
/*!****************************************************************!*\
  !*** ./src/app/pages/services/services.component.ngfactory.js ***!
  \****************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var i0 = __webpack_require__(/*! ./services.component.scss.shim.ngstyle */ "./src/app/pages/services/services.component.scss.shim.ngstyle.js");
var i1 = __webpack_require__(/*! @angular/core */ "@angular/core");
var i2 = __webpack_require__(/*! ./services.component */ "./src/app/pages/services/services.component.ts");
var styles_ServicesComponent = [i0.styles];
var RenderType_ServicesComponent = i1.ɵcrt({ encapsulation: 0, styles: styles_ServicesComponent, data: {} });
exports.RenderType_ServicesComponent = RenderType_ServicesComponent;
function View_ServicesComponent_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "p", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, [" services works!\n"]))], null, null); }
exports.View_ServicesComponent_0 = View_ServicesComponent_0;
function View_ServicesComponent_Host_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "app-services", [], null, null, null, View_ServicesComponent_0, RenderType_ServicesComponent)), i1.ɵdid(1, 114688, null, 0, i2.ServicesComponent, [], null, null)], function (_ck, _v) { _ck(_v, 1, 0); }, null); }
exports.View_ServicesComponent_Host_0 = View_ServicesComponent_Host_0;
var ServicesComponentNgFactory = i1.ɵccf("app-services", i2.ServicesComponent, View_ServicesComponent_Host_0, {}, {}, []);
exports.ServicesComponentNgFactory = ServicesComponentNgFactory;


/***/ }),

/***/ "./src/app/pages/services/services.component.scss.shim.ngstyle.js":
/*!************************************************************************!*\
  !*** ./src/app/pages/services/services.component.scss.shim.ngstyle.js ***!
  \************************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = ["\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiIsImZpbGUiOiJzcmMvYXBwL3BhZ2VzL3NlcnZpY2VzL3NlcnZpY2VzLmNvbXBvbmVudC5zY3NzIn0= */"];
exports.styles = styles;


/***/ }),

/***/ "./src/app/pages/services/services.component.ts":
/*!******************************************************!*\
  !*** ./src/app/pages/services/services.component.ts ***!
  \******************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var core_1 = __webpack_require__(/*! @angular/core */ "@angular/core");
var ServicesComponent = /** @class */ (function () {
    function ServicesComponent() {
    }
    ServicesComponent.prototype.ngOnInit = function () {
    };
    return ServicesComponent;
}());
exports.ServicesComponent = ServicesComponent;


/***/ }),

/***/ "./src/app/services/cache.service.ts":
/*!*******************************************!*\
  !*** ./src/app/services/cache.service.ts ***!
  \*******************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var i0 = __webpack_require__(/*! @angular/core */ "@angular/core");
var CacheService = /** @class */ (function () {
    function CacheService() {
    }
    CacheService.prototype.getCache = function (key) {
        var cacheVal = JSON.parse(localStorage.getItem(key));
        return cacheVal;
    };
    CacheService.prototype.setCache = function (key, val) {
        return localStorage.setItem(key, JSON.stringify(val));
    };
    CacheService.prototype.clearCache = function () {
        localStorage.clear();
    };
    CacheService.prototype.removeLocalKey = function (key) {
        localStorage.removeItem(key);
    };
    CacheService.prototype.getLength = function () {
        return localStorage.length;
    };
    CacheService.prototype.getSession = function (key) {
        return JSON.parse(sessionStorage.getItem(key));
    };
    CacheService.prototype.setSession = function (key, val) {
        return sessionStorage.setItem(key, JSON.stringify(val));
    };
    CacheService.prototype.clearSession = function () {
        sessionStorage.clear();
    };
    CacheService.prototype.removeSessionKey = function (key) {
        sessionStorage.removeItem(key);
    };
    CacheService.ngInjectableDef = i0.defineInjectable({ factory: function CacheService_Factory() { return new CacheService(); }, token: CacheService, providedIn: "root" });
    return CacheService;
}());
exports.CacheService = CacheService;


/***/ }),

/***/ "./src/app/services/event.service.ts":
/*!*******************************************!*\
  !*** ./src/app/services/event.service.ts ***!
  \*******************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var core_1 = __webpack_require__(/*! @angular/core */ "@angular/core");
var session_service_1 = __webpack_require__(/*! ./session.service */ "./src/app/services/session.service.ts");
var i0 = __webpack_require__(/*! @angular/core */ "@angular/core");
var i1 = __webpack_require__(/*! ./session.service */ "./src/app/services/session.service.ts");
var EventService = /** @class */ (function () {
    function EventService(sessionService) {
        this.loginEvent = new core_1.EventEmitter();
        this.loginEvent.subscribe(function (res) {
            console.log('login status ', res);
            sessionService.userLoggedIn = res;
        });
    }
    EventService.ngInjectableDef = i0.defineInjectable({ factory: function EventService_Factory() { return new EventService(i0.inject(i1.SessionService)); }, token: EventService, providedIn: "root" });
    return EventService;
}());
exports.EventService = EventService;


/***/ }),

/***/ "./src/app/services/http-service/interceptor.ts":
/*!******************************************************!*\
  !*** ./src/app/services/http-service/interceptor.ts ***!
  \******************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var core_1 = __webpack_require__(/*! @angular/core */ "@angular/core");
var http_1 = __webpack_require__(/*! @angular/common/http */ "@angular/common/http");
var rxjs_1 = __webpack_require__(/*! rxjs */ "rxjs");
var operators_1 = __webpack_require__(/*! rxjs/operators */ "rxjs/operators");
/**
 * @author Keyur Joshi
*/
var Interceptor = /** @class */ (function () {
    function Interceptor(injector) {
        this.injector = injector;
    }
    /**
     *
     * @param request
     * @param next
     */
    Interceptor.prototype.intercept = function (request, next) {
        var customReq;
        // clone the original header object
        customReq = request.clone({
            headers: request.headers
                .set("Accept", "application/json")
                .set("Access-Control-Allow-Credentials", "true")
                .set("Access-Control-Allow-Methods", "GET, POST,PUT")
                .set("Access-Control-Allow-Headers", "X-Requested-With,content-type")
                .set("Access-Control-Allow-Origin", "*")
        });
        console.log('requesr made for - ', customReq);
        return next.handle(request).pipe(operators_1.map(function (event) {
            if (event instanceof http_1.HttpResponse) {
                console.log('event--->>>', event);
            }
            return event;
        }), operators_1.catchError(function (error) {
            var data = {};
            data = {
                reason: error && error.error.reason ? error.error.reason : '',
                status: error.status
            };
            return rxjs_1.throwError(error);
        }));
    };
    return Interceptor;
}());
exports.Interceptor = Interceptor;


/***/ }),

/***/ "./src/app/services/session.service.ts":
/*!*********************************************!*\
  !*** ./src/app/services/session.service.ts ***!
  \*********************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var i0 = __webpack_require__(/*! @angular/core */ "@angular/core");
var SessionService = /** @class */ (function () {
    function SessionService() {
    }
    Object.defineProperty(SessionService.prototype, "userLoggedIn", {
        get: function () {
            return this._userLoggedIn;
        },
        set: function (val) {
            this._userLoggedIn = val;
        },
        enumerable: true,
        configurable: true
    });
    SessionService.ngInjectableDef = i0.defineInjectable({ factory: function SessionService_Factory() { return new SessionService(); }, token: SessionService, providedIn: "root" });
    return SessionService;
}());
exports.SessionService = SessionService;


/***/ }),

/***/ "./src/app/services/toast.service.ts":
/*!*******************************************!*\
  !*** ./src/app/services/toast.service.ts ***!
  \*******************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var i0 = __webpack_require__(/*! @angular/core */ "@angular/core");
var ToastService = /** @class */ (function () {
    function ToastService() {
        this.toastObj = {
            isShow: false,
            toastMsg: '',
            toastType: 'alert-info'
        };
    }
    ToastService.prototype.presentToastInfo = function (msg, time) {
        var _this = this;
        if (time === void 0) { time = 3000; }
        this.toastObj.isShow = true;
        this.toastObj.toastMsg = msg;
        this.toastObj.toastType = 'alert-info';
        setTimeout(function () {
            _this.toastObj.isShow = false;
        }, time);
    };
    ToastService.prototype.presentToastDanger = function (msg, time) {
        var _this = this;
        if (time === void 0) { time = 3000; }
        this.toastObj.isShow = true;
        this.toastObj.toastMsg = msg;
        this.toastObj.toastType = 'alert-danger';
        setTimeout(function () {
            _this.toastObj.isShow = false;
        }, time);
    };
    ToastService.prototype.presentToastWarning = function (msg, time) {
        var _this = this;
        if (time === void 0) { time = 3000; }
        this.toastObj.isShow = true;
        this.toastObj.toastMsg = msg;
        this.toastObj.toastType = 'alert-warning';
        setTimeout(function () {
            _this.toastObj.isShow = false;
        }, time);
    };
    ToastService.ngInjectableDef = i0.defineInjectable({ factory: function ToastService_Factory() { return new ToastService(); }, token: ToastService, providedIn: "root" });
    return ToastService;
}());
exports.ToastService = ToastService;


/***/ }),

/***/ "./src/main.server.ts":
/*!****************************!*\
  !*** ./src/main.server.ts ***!
  \****************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var app_server_module_ngfactory_1 = __webpack_require__(/*! ./app/app.server.module.ngfactory */ "./src/app/app.server.module.ngfactory.js");
exports.AppServerModuleNgFactory = app_server_module_ngfactory_1.AppServerModuleNgFactory;
var app_server_module_1 = __webpack_require__(/*! ./app/app.server.module */ "./src/app/app.server.module.ts");
exports.AppServerModule = app_server_module_1.AppServerModule;
exports.LAZY_MODULE_MAP = {};


/***/ }),

/***/ 0:
/*!**********************************!*\
  !*** multi ./src/main.server.ts ***!
  \**********************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

module.exports = __webpack_require__(/*! /Users/test/Desktop/Demo_Apps/Angular Apps/giggada/giggada/src/main.server.ts */"./src/main.server.ts");


/***/ }),

/***/ "@angular/animations":
/*!**************************************!*\
  !*** external "@angular/animations" ***!
  \**************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/animations");

/***/ }),

/***/ "@angular/animations/browser":
/*!**********************************************!*\
  !*** external "@angular/animations/browser" ***!
  \**********************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/animations/browser");

/***/ }),

/***/ "@angular/common":
/*!**********************************!*\
  !*** external "@angular/common" ***!
  \**********************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/common");

/***/ }),

/***/ "@angular/common/http":
/*!***************************************!*\
  !*** external "@angular/common/http" ***!
  \***************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/common/http");

/***/ }),

/***/ "@angular/core":
/*!********************************!*\
  !*** external "@angular/core" ***!
  \********************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/core");

/***/ }),

/***/ "@angular/forms":
/*!*********************************!*\
  !*** external "@angular/forms" ***!
  \*********************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/forms");

/***/ }),

/***/ "@angular/http":
/*!********************************!*\
  !*** external "@angular/http" ***!
  \********************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/http");

/***/ }),

/***/ "@angular/platform-browser":
/*!********************************************!*\
  !*** external "@angular/platform-browser" ***!
  \********************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/platform-browser");

/***/ }),

/***/ "@angular/platform-browser/animations":
/*!*******************************************************!*\
  !*** external "@angular/platform-browser/animations" ***!
  \*******************************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/platform-browser/animations");

/***/ }),

/***/ "@angular/platform-server":
/*!*******************************************!*\
  !*** external "@angular/platform-server" ***!
  \*******************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/platform-server");

/***/ }),

/***/ "@angular/router":
/*!**********************************!*\
  !*** external "@angular/router" ***!
  \**********************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/router");

/***/ }),

/***/ "@nguniversal/module-map-ngfactory-loader":
/*!***********************************************************!*\
  !*** external "@nguniversal/module-map-ngfactory-loader" ***!
  \***********************************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@nguniversal/module-map-ngfactory-loader");

/***/ }),

/***/ "rxjs":
/*!***********************!*\
  !*** external "rxjs" ***!
  \***********************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("rxjs");

/***/ }),

/***/ "rxjs/operators":
/*!*********************************!*\
  !*** external "rxjs/operators" ***!
  \*********************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("rxjs/operators");

/***/ }),

/***/ "tslib":
/*!************************!*\
  !*** external "tslib" ***!
  \************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("tslib");

/***/ })

/******/ })));
//# sourceMappingURL=main.js.map